id: P009573
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1CZ1073
  title: མགོན་པོའི་བེའུ་བུམ་སྙིང་ཐིག་བཀའ་རྒྱ་མ།
  author: ''
  volumes:
    e8c1cab5db55457c9716be46a1018f19:
      image_group_id: I1CZ1437
      title: ''
      volume_number: 1
      total_pages: 34
      base_file: v001.txt
