id: I7D1F8224
legacy_id: P009573
ocr_import_info:
  bdrc_scan_id: W1CZ1073
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T10:49:07'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T18:48:15.768966+00:00'
last_modified: 2022-08-31 02:48:25.114956
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1CZ1073
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1CZ1073
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: མགོན་པོའི་བེའུ་བུམ་སྙིང་ཐིག་བཀའ་རྒྱ་མ།
  author: མཁས་གྲུབ་རྗེ་དགེ་ལེགས་དཔལ་བཟང་།
statistics:
  ocr_word_mean_confidence_index: 0.44103220084783334
  ocr_word_median_confidence_index: 0.33000001311302185
quality: null
bases:
  I1CZ1437:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1CZ1437
      total_pages: 34
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1CZ1437.txt
    statistics:
      ocr_word_median_confidence_index: 0.33000001311302185
      ocr_word_mean_confidence_index: 0.44103220084783334
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
